{{- if .Values.enabled }}
{{- if .Values.rest }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "spaceone.labels" . | indent 4 }}
    spaceone.service: {{ .Values.name }}
  name: {{ .Values.name }}-rest
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas_worker | default .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      spaceone.service: {{ .Values.name }}-rest
  template:
    metadata:
      annotations:
        spaceone.deployment.tool: helm
        spaceone.database-flag: {{ print .Values.database | sha256sum }}
        spaceone.shared-flag: {{ print .Values.global.shared | sha256sum }}
        spaceone.application-flag: {{ print .Values.application_rest | sha256sum }}
      labels:
{{ include "spaceone.labels" . | indent 8 }}
        spaceone.service: {{ .Values.name }}-rest
    spec:
{{- if .Values.global.serviceAccountName }}
      serviceAccountName: {{ .Values.global.serviceAccountName }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
      containers:
        - name: {{ .Values.name }}-fastapi
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ['spaceone', 'rest', 'spaceone.{{ regexReplaceAll "-" .Values.name "_" }}', '-p', '8000']
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: default-conf
              mountPath: /opt/spaceone/{{ .Values.name }}/config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: timezone
              mountPath: /etc/localtime
            - name: log-volume
              mountPath: /var/log/spaceone
            - name: database-conf
              mountPath: /opt/spaceone/{{ .Values.name }}/config/database.yaml
              subPath: database.yaml
              readOnly: true
            - name: shared-conf
              mountPath: /opt/spaceone/{{ .Values.name }}/config/shared.yaml
              subPath: shared.yaml
              readOnly: true
            - name: application-conf
              mountPath: /opt/spaceone/{{ .Values.name }}/config/application.yaml
              subPath: application.yaml
              readOnly: true
{{- if .Values.volumeMounts.application_rest }}
{{- toYaml .Values.volumeMounts.application_rest | nindent 12 }}
{{- end }}
          env:
            - name: SPACEONE_CONFIG_FILE
              value: /opt/spaceone/{{ .Values.name }}/config/config.yaml

        - name: {{ .Values.name }}-nginx
          image: 'nginx:stable'
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: default-conf
              mountPath: /opt/spaceone/{{ .Values.name }}/config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: timezone
              mountPath: /etc/localtime
            - name: log-volume
              mountPath: /var/log/spaceone
            - name: rest-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: rest-nginx-proxy-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true


{{- if .Values.sidecar }}
{{- toYaml .Values.sidecar | nindent 8 }}
{{- end }}

{{- if .Values.global.backend.sidecar }}
{{- toYaml .Values.global.backend.sidecar | nindent 8 }}
{{- end }}

      volumes:
        - name: default-conf
          configMap:
            name: {{ .Values.name }}-conf
        - name: database-conf
          configMap:
            name: {{ .Values.name }}-database-conf
        - name: shared-conf
          configMap:
            name: shared-conf
        - name: application-conf
          configMap:
            name: {{ .Values.name }}-application-rest-conf
        - name: rest-nginx-conf
          configMap:
            name: {{ .Values.name }}-rest-nginx-conf
        - name: rest-nginx-proxy-conf
          configMap:
            name: {{ .Values.name }}-rest-nginx-proxy-conf

{{- if .Values.volumes }}
{{- toYaml .Values.volumes | nindent 8 }}
{{- end }}

{{- if .Values.global.backend.volumes }}
{{- toYaml .Values.global.backend.volumes | nindent 8 }}
{{- end }}

{{- if .Values.pod.spec }}
{{- toYaml .Values.pod.spec | nindent 6 }}
{{- end }}

{{- end }}
{{- end }}
