{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-nginx-proxy-conf
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  proxy.conf: |-
{{ .Files.Get "config/proxy.conf" | nindent 4 }}
{{- end }}