{{- if .Values.global.shared_secret.create }}
{{ if not (lookup "v1" "Secret" .Release.Namespace "shared-secret" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  shared_secret.yaml: |-
{{- toYaml .Values.global.shared_secret | nindent 4 }}
{{- end }}
{{- end }}