name: SpaceONE CI commit push
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_PREFIX: pyengine
  SERVICE: inventory
  LOCATION_VERSION: src # the location for VERSION file (ex- . means the location of VERSION is ./VERSION)
  LOCATION_DOCKERFILE: .

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.job1.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: calculate_version
        id: job1
        run: |
          echo "::set-output name=VERSION::$(cat $LOCATION_VERSION/VERSION).${{ github.run_id }}"

  docker:
    if: github.repository_owner == 'spaceone-dev'
    needs: initialize
    env:
      VERSION: ${{ needs.initialize.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload docker
        uses: docker/build-push-action@v1
        with:
          path: ${{ env.LOCATION_DOCKERFILE }}
          repository: ${{ env.IMAGE_PREFIX }}/${{ env.SERVICE }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest,${{ env.VERSION }}
          
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}