name: SpaceONE CI

on:
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set environment virables
      run: |
        echo "::set-env name=IMAGE_PREFIX::spaceone"
        echo "::set-env name=SERVICE::inventory"
        echo "::set-env name=LOCATION_SETUP_PY::src"
        echo "::set-env name=LOCATION_DOCKERFILE::."

        version=$(cat src/VERSION)-${{ github.run_id }}
        echo "::set-env name=VERSION::$version"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build
      run: |
        echo "Building pypi ..."
        cd $LOCATION_SETUP_PY
        python3 setup.py bdist_wheel

    - name: Test
      id: test
      run: |
        echo "Running test ... None"
        # fail test or pass test

    - name: Upload Pypi
      id: upload
      run: |
        cd $LOCATION_SETUUP_PY
        twine upload dist/*.whl --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --verbose
      # continue next jobs though this job fails
      continue-on-error: true

    - name: Merge branch automatically
      if: steps.test.outcome == 'success'
      uses: pascalgn/automerge-action@v0.8.3
      env:
        # can not run workflow with new repository token.
        GITHUB_TOKEN: ${{secrets.REPOSITORY_CONTROL_ACCESS_KEY}}
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        MERGE_LABELS: ""

    - name: Notify to slack
      if: always() # Pick up events even if the job fails or is canceled.
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: "[BOT]"
        fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required