name: SpaceONE Docker upload

on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set environment virables
      run: |
        echo "::set-env name=IMAGE_PREFIX::spaceone"
        echo "::set-env name=SERVICE::inventory"
        echo "::set-env name=LOCATION_DOCKERFILE::."
        version=$(cat src/VERSION)-${{ github.run_id }}
        echo "::set-env name=VERSION::$version"

    - name: Upload docker
      uses: docker/build-push-action@v1
      with:
        repository: ${{ env.IMAGE_PREFIX }}/${{ env.SERVICE }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ${{ env.LOCATION_DOCKERFILE }}
        tags: latest,${{ env.VERSION }}